apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent
labels:
  - pairs:
      app.kubernetes.io/part-of: mcp-agent
resources:
  - serviceaccounts.yaml
  - agent.yaml
  - otel-collector.yaml
  - networkpolicy.yaml
